apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scichat-loopback.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ include "scichat-loopback.name" . }}
data:
  config.local.js: |-
{{ .Files.Get "envfiles/config.local.js" | indent 4 }}
  {{- if eq .Release.Namespace "production" }}
  datasources.json: |-
{{ .Files.Get "envfiles/datasources.production.json" | indent 4 }}
  {{- else if eq .Release.Namespace "qa" }}
  datasources.json: |-
{{ .Files.Get "envfiles/datasources.qa.json" | indent 4 }}
  {{- else }}
  datasources.json: |-
{{ .Files.Get "envfiles/datasources.dev.json" | indent 4 }}
  {{- end }}

