apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scichat-loopback.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ include "scichat-loopback.name" . }}
data:
{{- if eq .Release.Namespace "production" }}
  .env: |-
{{ .Files.Get "envfiles/.env.production" | indent 4 }}
{{- else if eq .Release.Namespace "dev" }}
  .env: |-
{{ .Files.Get "envfiles/.env.dev" | indent 4 }}
{{- end }}

